name: Release

on:
  push:
    tags:
      - '*'
    branches: [ main ]


jobs:
  build:
    name: Release binary
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   target: x86_64-unknown-linux-gnu
          #   artifact_name: main
          #   asset_name: main-x86_64-unknown-linux-gnu
          # - os: ubuntu-latest
          #   target: x86_64-unknown-linux-musl
          #   artifact_name: main
          #   asset_name: main-x86_64-unknown-linux-musl
          # - os: ubuntu-latest
          #   target: x86_64-pc-windows-gnu
          #   artifact_name: main.exe
          #   asset_name: main-x86_64-pc-windows-gnu.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: main
            asset_name: main-x86_64-apple-darwin


    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # - name: Install mysql client if ubuntu
      #   if: runner.os == 'Linux'
      #   run: |
      #     wget https://dev.mysql.com/get/mysql-apt-config_0.8.15-1_all.deb
      #     sudo dpkg -i mysql-apt-config_0.8.15-1_all.deb
      #     sudo apt-get update
      #     sudo apt-get install libmysqlclient-dev

      - name: Install mysql client if macos
        if: runner.os == 'macOS'
        run: |
          brew install mysql-client
          echo '~1~~~~~~~~~~~~~~~~~~~~~~~~~'
          brew ls mysql-client
          export LDFLAGS="-L/usr/local/opt/mysql-client/lib"
          # export CPPFLAGS="-I/usr/local/opt/mysql-client/include"
          # export PKG_CONFIG_PATH="/usr/local/opt/mysql-client/lib/pkgconfig"
          echo '~2~~~~~~~~~~~~~~~~~~~~~~~~~'
          # echo 'export PATH="/usr/local/opt/mysql-client/bin:$PATH"' >> /Users/runner/.bash_profile
          # source ~/.bash_profile
          # echo '~3~~~~~~~~~~~~~~~~~~~~~~~~~'

      - name: Cross build with all features
        uses: actions-rs/cargo@v1
        uses: shogo82148/actions-setup-mysql@v1
        with:
          use-cross: true 
          command: build
          args: --release --target ${{ matrix.target }} --all-features --verbose

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.1.1
        with:
          command: ls target/${{ matrix.target }}/release/
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
